<a href="https://colab.research.google.com/github/samud07/samud07/blob/main/Book_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import files
 
 
uploaded = files.upload()

Saving Books.csv to Books.csv

In [4]:
import pandas as pd
import io
 
df = pd.read_csv(io.BytesIO(uploaded['Books.csv']))
print(df)

              ISBN                                         Book-Title  \
0       0195153448                                Classical Mythology
1       0002005018                                       Clara Callan
2       0060973129                               Decision in Normandy
3       0374157065  Flu: The Story of the Great Influenza Pandemic...
4       0393045218                             The Mummies of Urumchi
...            ...                                                ...
271355  0440400988                         There's a Bat in Bunk Five
271356  0525447644                            From One to One Hundred
271357  006008667X  Lily Dale : The True Story of the Town that Ta...
271358  0192126040                        Republic (World's Classics)
271359  0767409752  A Guided Tour of Rene Descartes' Meditations o...

                 Book-Author Year-Of-Publication  \
0         Mark P. O. Morford                2002
1       Richard Bruce Wright                2001
2               Carlo D'Este                1991
3           Gina Bari Kolata                1999
4            E. J. W. Barber                1999
...                      ...                 ...
271355        Paula Danziger                1988
271356            Teri Sloat                1991
271357      Christine Wicker                2004
271358                 Plato                1996
271359   Christopher  Biffle                2000

                                               Publisher  \
0                                Oxford University Press
1                                  HarperFlamingo Canada
2                                        HarperPerennial
3                                   Farrar Straus Giroux
4                             W. W. Norton &amp; Company
...                                                  ...
271355                   Random House Childrens Pub (Mm)
271356                                      Dutton Books
271357                                HarperSanFrancisco
271358                           Oxford University Press
271359  McGraw-Hill Humanities/Social Sciences/Languages

                                              Image-URL-S  \
0       http://images.amazon.com/images/P/0195153448.0...
1       http://images.amazon.com/images/P/0002005018.0...
2       http://images.amazon.com/images/P/0060973129.0...
3       http://images.amazon.com/images/P/0374157065.0...
4       http://images.amazon.com/images/P/0393045218.0...
...                                                   ...
271355  http://images.amazon.com/images/P/0440400988.0...
271356  http://images.amazon.com/images/P/0525447644.0...
271357  http://images.amazon.com/images/P/006008667X.0...
271358  http://images.amazon.com/images/P/0192126040.0...
271359  http://images.amazon.com/images/P/0767409752.0...

                                              Image-URL-M  \
0       http://images.amazon.com/images/P/0195153448.0...
1       http://images.amazon.com/images/P/0002005018.0...
2       http://images.amazon.com/images/P/0060973129.0...
3       http://images.amazon.com/images/P/0374157065.0...
4       http://images.amazon.com/images/P/0393045218.0...
...                                                   ...
271355  http://images.amazon.com/images/P/0440400988.0...
271356  http://images.amazon.com/images/P/0525447644.0...
271357  http://images.amazon.com/images/P/006008667X.0...
271358  http://images.amazon.com/images/P/0192126040.0...
271359  http://images.amazon.com/images/P/0767409752.0...

                                              Image-URL-L
0       http://images.amazon.com/images/P/0195153448.0...
1       http://images.amazon.com/images/P/0002005018.0...
2       http://images.amazon.com/images/P/0060973129.0...
3       http://images.amazon.com/images/P/0374157065.0...
4       http://images.amazon.com/images/P/0393045218.0...
...                                                   ...
271355  http://images.amazon.com/images/P/0440400988.0...
271356  http://images.amazon.com/images/P/0525447644.0...
271357  http://images.amazon.com/images/P/006008667X.0...
271358  http://images.amazon.com/images/P/0192126040.0...
271359  http://images.amazon.com/images/P/0767409752.0...

[271360 rows x 8 columns]

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
from google.colab import files
 
 
uploaded = files.upload()

Saving Ratings.csv to Ratings.csv

In [6]:
import pandas as pd
import io
 
df = pd.read_csv(io.BytesIO(uploaded['Ratings.csv']))
print(df)

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [7]:
from google.colab import files
 
 
uploaded = files.upload()

Saving Users.csv to Users.csv

In [24]:
import pandas as pd
import io
 
df = pd.read_csv(io.BytesIO(uploaded['Users.csv']))
print(df)

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [25]:
Books_data=pd.read_csv('Books.csv')
Ratings_data=pd.read_csv('Ratings.csv')
Users_data=pd.read_csv('Users.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [27]:
Books_data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

Warning: total number of rows (271360) exceeds max_rows (20000). Limiting to first (20000) rows.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [29]:
Ratings_data

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

Warning: total number of rows (1149780) exceeds max_rows (20000). Limiting to first (20000) rows.

In [23]:
Users_data

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

Warning: total number of rows (278858) exceeds max_rows (20000). Limiting to first (20000) rows.

In [32]:
print(Books_data.shape)
print(Ratings_data.shape) 
print(Users_data.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [33]:
Books_data.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [34]:
Ratings_data.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [35]:
Users_data.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [36]:
Books_data.duplicated().sum()

0

In [37]:
Ratings_data.duplicated().sum()

0

In [38]:
Users_data.duplicated().sum()

0

Popularity Based Recommender System

In [40]:
Ratings_with_name = Ratings_data.merge(Books_data,on='ISBN')

In [41]:
Ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

Warning: total number of rows (1031136) exceeds max_rows (20000). Limiting to first (20000) rows.

In [43]:
Ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

Warning: total number of rows (241071) exceeds max_rows (20000). Limiting to first (20000) rows.

In [44]:
Numbers_Ratings_df = Ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
Numbers_Ratings_df.rename(columns={'Book-Rating':'Numbers_Ratings'},inplace=True)
Numbers_Ratings_df

                                               Book-Title  Numbers_Ratings
0        A Light in the Storm: The Civil War Diary of ...                4
1                                   Always Have Popsicles                1
2                    Apple Magic (The Collector's series)                1
3        Ask Lily (Young Women of Faith: Lily Series, ...                1
4        Beyond IBM: Leadership Marketing and Finance ...                1
...                                                   ...              ...
241066                                      Ã?Â?lpiraten.                2
241067                     Ã?Â?rger mit Produkt X. Roman.                4
241068                                Ã?Â?sterlich leben.                1
241069                              Ã?Â?stlich der Berge.                3
241070                                  Ã?Â?thique en toc                2

[241071 rows x 2 columns]

Warning: total number of rows (241071) exceeds max_rows (20000). Limiting to first (20000) rows.

In [45]:
Average_Ratings_df = Ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
Average_Ratings_df.rename(columns={'Book-Rating':'Average_Ratings'},inplace=True)
Average_Ratings_df

                                               Book-Title  Average_Ratings
0        A Light in the Storm: The Civil War Diary of ...         2.250000
1                                   Always Have Popsicles         0.000000
2                    Apple Magic (The Collector's series)         0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...         8.000000
4        Beyond IBM: Leadership Marketing and Finance ...         0.000000
...                                                   ...              ...
241066                                      Ã?Â?lpiraten.         0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.         5.250000
241068                                Ã?Â?sterlich leben.         7.000000
241069                              Ã?Â?stlich der Berge.         2.666667
241070                                  Ã?Â?thique en toc         4.000000

[241071 rows x 2 columns]

Warning: total number of rows (241071) exceeds max_rows (20000). Limiting to first (20000) rows.

In [46]:
Popular_df = Numbers_Ratings_df.merge(Average_Ratings_df,on='Book-Title')
Popular_df

,Book-Title,Numbers_Ratings,Average_Ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

Warning: total number of rows (241071) exceeds max_rows (20000). Limiting to first (20000) rows.

In [49]:
Popular_df = Popular_df[Popular_df['Numbers_Ratings']>=250].sort_values('Average_Ratings',ascending=False).head(50)

In [50]:
Popular_df

,Book-Title,Numbers_Ratings,Average_Ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [53]:
Popular_df.merge(Books_data,on='Book-Title')

,Book-Title,Numbers_Ratings,Average_Ratings,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
1,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136369,J. K. Rowling,2001,Scholastic,http://images.amazon.com/images/P/0439136369.0...,http://images.amazon.com/images/P/0439136369.0...,http://images.amazon.com/images/P/0439136369.0...
2,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0786222743,J. K. Rowling,2000,Thorndike Press,http://images.amazon.com/images/P/0786222743.0...,http://images.amazon.com/images/P/0786222743.0...,http://images.amazon.com/images/P/0786222743.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
4,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139600,J. K. Rowling,2002,Scholastic Paperbacks,http://images.amazon.com/images/P/0439139600.0...,http://images.amazon.com/images/P/0439139600.0...,http://images.amazon.com/images/P/0439139600.0...
...,...,...,...,...,...,...,...,...,...,...
191,Lord of the Flies,259,3.818533,0698102193,William G. Golding,1978,Putnam Pub Group,http://images.amazon.com/images/P/0698102193.0...,http://images.amazon.com/images/P/0698102193.0...,http://images.amazon.com/images/P/0698102193.0...
192,A Prayer for Owen Meany,413,3.796610,0345361792,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...
193,A Prayer for Owen Meany,413,3.796610,0345363523,John Irving,1989,Ballantine Books,http://images.amazon.com/images/P/0345363523.0...,http://images.amazon.com/images/P/0345363523.0...,http://images.amazon.com/images/P/0345363523.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409,0345313860,ANNE RICE,1986,Ballantine Books,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),356,3.772472,0316284955,Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...

In [55]:
Popular_df = Popular_df.merge(Books_data,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','Numbers_Ratings','Average_Ratings']]

In [56]:
Popular_df

,Book-Title,Book-Author,Image-URL-M,Numbers_Ratings,Average_Ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472